export enum ErrorCode {
	none = 'none',
	missingField = 'missingField',
	invalidData = 'invalidData',
	insufficientAccess = 'insufficientAccess',
	bodyMissing = 'bodyMissing',
	missingObjType = 'missingObjType',
	missingBody = 'missingBody',
	unauthorized = 'unauthorized',
	loginTimeout = 'loginTimout',
	recordNotFound = 'recordNotFound',
	notFound = 'notFound',
	notCreatable = 'notCreatable',
	notDeletable = 'notDeletable',
	notUpdatable = 'notUpdatable',
	notQueryable = 'notQueryable',
	invalidField = 'invalidField',
	limitExceeded = 'limitExceeded',
	invalidAuthentication = 'invalidAuthentication',
	unknownException = 'UNKNOWN_EXCEPTION'
}
